### ISSUE TITLE
'gen_qrcode' is undefined

### ISSUE THREAD

**Issue by moayyaed** [ascorbic-acid/qrcode_gen#1]
After install the app to my site i got this error

jinja2.exceptions.UndefinedError: 'gen_qrcode' is undefined

![image](https://github.com/Ebkarlibya/qrcode_gen/assets/13677197/f6fe1009-996e-42f6-b33e-1ba4a4fb75fd)
![image](https://github.com/Ebkarlibya/qrcode_gen/assets/13677197/4e05bab5-6dc7-42a7-8844-651b8c2c2407)

Server Error
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1689, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: gen_qrcode() missing 1 required positional argument: 'text'

**Comment by ascorbic-acid** [comment]
hello, did you do bench migrate & bench restart after installing the app and how you are using "gen_qrcode()", in a print format ?

**Comment by moayyaed** [comment]
thank you for your reply
yes, i did .
i follow https://devbo.medium.com/how-to-print-qrcode-in-erpnext-print-format-40529f89e710 to make print

**Comment by ascorbic-acid** [comment]
the error saying that you did not supply the text argument to the function, try this and see if it works

```
<img src="{{ gen_qrcode('test123') }}" width="100" />

```
